### ISSUE TITLE
Unable to pull image ghcr.io/hoellen/nextcloud

### ISSUE THREAD

**Issue by lexxxel** [hoellen/docker-nextcloud#1]
I'm not able to pull the image, even after login ghcr.io with my account. Is this an error on my end or are there permissions on your side not set correctly? Also in the README the nextcloud version (21) is wrong. It should be 23, right?

**Comment by waja** [comment]
cause there is no package (until now): https://github.com/hoellen?tab=packages

**Comment by hoellen** [comment]
The package visibility was private. It is now public.
