### ISSUE TITLE
Nextcloud is not installed - only a limited number of commands are available

### ISSUE THREAD

**Issue by waja** [hoellen/docker-nextcloud#10]
Hi @hoellen,

creating a new instance resulted into:

```
nextcloud_1            | Starting automatic configuration...
nextcloud_1            | Automatic configuration finished.
nextcloud_1            | Nextcloud is not installed - only a limited number of commands are available
nextcloud_1            |
nextcloud_1            |
nextcloud_1            |  Command "app:disable" is not defined.
nextcloud_1            |
nextcloud_1            |
nextcloud_1            |  Do you want to run "app:check-code" instead?  (yes/no) [no]:
nextcloud_1            |  > Exception: Not installed in /nextcloud/lib/base.php:277
nextcloud_1            | Stack trace:
nextcloud_1            | #0 /nextcloud/lib/base.php(649): OC::checkInstalled(Object(OC\SystemConfig))
nextcloud_1            | #1 /nextcloud/lib/base.php(1087): OC::init()
nextcloud_1            | #2 /nextcloud/cron.php(43): require_once('/nextcloud/lib/...')
nextcloud_1            | #3 {main}
```

Looks like it's the same issue like https://github.com/Wonderfall/docker-nextcloud/issues/90. Maybe I'm doing something wrong? Can't imagine that a real issue over there is unfixed since 4 month?

**Comment by waja** [comment]
okay ... investigating from the inside of the container there seems to be an issue with updating the config (https://github.com/hoellen/docker-nextcloud/blob/master/rootfs/usr/local/bin/setup.sh#L63-L79)

```
/nextcloud $ ls -la /tmp/
total 12
drwxrwxrwt    1 root     root          4096 Jan 12 16:37 .
drwxr-xr-x    1 root     root          4096 Jan 12 16:37 ..
-rw-------    1 nextclou nextclou        82 Jan 12 16:37 tmp.JljFKg
/nextcloud $ cat /tmp/tmp.JljFKg

Parse error: syntax error, unexpected token "/" in Standard input code on line 2
```

Even `/nextcloud/config/autoconfig.php` exists and is not merged into `/nextcloud/config/config.php`.

**Comment by waja** [comment]
removing https://github.com/hoellen/docker-nextcloud/blob/master/rootfs/usr/local/bin/setup.sh#L69 seems to fix the issue? ;)

```
/nextcloud $ /usr/local/bin/setup.sh
Starting automatic configuration...
Automatic configuration finished.
firstrunwizard 2.12.0 disabled
/nextcloud $
```

**Comment by waja** [comment]
> removing https://github.com/hoellen/docker-nextcloud/blob/master/rootfs/usr/local/bin/setup.sh#L69 seems to fix the issue?

hmm ... no ... just running `/usr/local/bin/setup.sh` second time seems to fix it?

**Comment by hoellen** [comment]
Thanks for investigating and sending a PR.
