### ISSUE TITLE
On 24.0.4 image, "php -i" is only showing 128M for the memory_limit

### ISSUE THREAD

**Issue by mhbates** [hoellen/docker-nextcloud#25]
Not sure if this is a bug. The other environment variables like `APC_SHM_SIZE` and `OPCACHE_MEM_SIZE` are reflected correctly in `php -i`.

**Comment by hoellen** [comment]
The environment variable `MEMORY_LIMIT` is set for php-fpmm which is an alternative FastCGI daemon for PHP. You can verify this by running `php-fpm -tt` in your container.
Please feel free to open the issue again, if you still think its a bug.
