### ISSUE TITLE
Issue with iOS Reminders and the Suspicious Login app

### ISSUE THREAD

**Issue by mhbates** [hoellen/docker-nextcloud#27]
I'm posting this here in case this ends up being an issue with this container as well, like that PHP hardening issue I previously reported. It doesn't seem like others with the Suspicious Login app are getting these kinds of errors, so it could be this container. Any ideas?

https://github.com/nextcloud/suspicious_login/issues/695

**Comment by waja** [comment]
What I can tell you about this:

```
# grep SuspiciousLogin data/nextcloud.log
# docker ps | grep hoellen
311b67b38935   ghcr.io/hoellen/nextcloud:24                   "docker-php-entrypoi…"   2 days ago     Up 2 days               8888/tcp, 9000/tcp                                                                                                                                                                                                                  nextcloud-nextcloud-1
#
```

**Comment by mhbates** [comment]
Looks like this is a Suspicious Login issue with PHP 8.1 compatibility. Closing.
