### ISSUE TITLE
Migrating from old image fails on startup

### ISSUE THREAD

**Issue by mwlczk** [hoellen/docker-nextcloud#28]
Starting automatic configuration...
Automatic configuration finished.
Exception: Not installed in /nextcloud/lib/base.php:277
Stack trace:
#0 /nextcloud/lib/base.php(656): OC::checkInstalled(Object(OC\SystemConfig))
#1 /nextcloud/lib/base.php(1096): OC::init()
#2 /nextcloud/cron.php(43): require_once('/nextcloud/lib/...')
#3 {main}

Upgrading from the old image https://github.com/hoellen/dockerfiles/tree/master/nextcloud to this one here.
DB is run seperately, so this could be a different bug than #10

**Comment by hoellen** [comment]
You probably didn't change the volume locations in your `docker-compose.yml`.
That's the reason the automatic configuration tries to run and failes.

Please use the following migration guide:

> From now on you'll need to make sure all volumes have proper permissions. The default UID/GID is now 1000, so you'll need to build the image yourself if you want to change that, or you can just change the actual permissions of the volumes using chown -R 1000:1000. The flexibility provided by the legacy image came at some cost (performance & security), therefore this feature won't be provided anymore.
> 
> Other changes that should be reflected in your configuration files:
> 
>     /config volume is now /nextcloud/config
>     /apps2 volume is now /nextcloud/apps2
>     ghcr.io/wonderfall/nextcloud is the new image location
> 
> You should edit your docker-compose.yml and config.php accordingly.
