### ISSUE TITLE
Adding ffmpeg

### ISSUE THREAD

**Issue by thiesschneider** [hoellen/docker-nextcloud#35]
Hey,

I wanted to add the App "[memories](https://github.com/pulsejet/memories)" which looks like something everybody wants to have ;) ([reddit post](https://www.reddit.com/r/selfhosted/comments/z245mo/loading_40k_images_in_one_view_with_memories/)). To make it run, I had to disable the PHP_HARDENING (I dont know, perhaps this can also run with it enabled with some tweaking?). 

Now I wanted to add the extensions for the media types but unfortunately ffmpeg is not installed.
Can you add it, or a possibility to add it via variables? I saw it in some [commit](https://github.com/hoellen/docker-nextcloud/commit/fed2d9b9b775bf4b52b81caaf62181a0e636aeed) from the past, but it did not survive...

Thanks!

**Comment by hoellen** [comment]
Sorry, I will not add `ffmpeg` to this image, as we cannot add dependencies for everyone.
I want to keep this image simple and lean.
The easiest solution for you would be to build your own image based on this one:
```
FROM ghcr.io/hoellen/nextcloud:25
RUN apk -U add ffmpeg
```


Or run this command when the container is running:
```
docker exec -it --user root nextcloud apk -U add ffmpeg
```

**Comment by archont00** [comment]
Got here via Google, it may help some.

@thiesschneider: Rather than disabling the PHP_HARDENING completely, you may want to add white list items to let HARDENING ignore memories app.

```
/usr/local/etc/php/conf.d/nextcloud-php8.rules                                                                                            
                                                                                                                                          
# Nextcloud whitelist (tested with Nextcloud 25.0.0)                                                                                      
sp.disable_function.function("shell_exec").param("command").filename("/nextcloud/apps2/memories/lib/Util.php").allow();                   
sp.disable_function.function("shell_exec").param("command").filename("/nextcloud/apps2/memories/lib/Service/BinExt.php").allow();         
```

Either manually in running container or add some `sed` stuff to you own build file.
