### ISSUE TITLE
No database connection

### ISSUE THREAD

**Issue by thiesschneider** [hoellen/docker-nextcloud#58]
Hey there,

since the [commit 8070434](https://github.com/hoellen/docker-nextcloud/commit/80704341e66942669c4ca01282b7a2eac5491fbd) I do get the log message: `waiting for the database container...` and the container is not starting. I use a postgres database and it was and is connectable from within the nextcloud container. When I do `occ upgrade` for example the response is 
```
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <calendar> ...
Updated <calendar> to 4.6.1
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
```
so I assume nextcloud itself can access the database.

Do you have an idea how to fix this?

thx!

**Comment by waja** [comment]
If you enter your Nextcloud container, what is in the values DB_TYPE, DB_PORT and DB_HOST?

**Comment by thiesschneider** [comment]
Hey @waja,

I did not specify DB_PORT, which I added now (5432) and now it is working again. It did work without before, but good to know now!

Thank you.

**Comment by hoellen** [comment]
The new database check at startup now has the correct default port for Postgres (https://github.com/hoellen/docker-nextcloud/commit/0ee7e16b13be131e7620e0fd5059c1491a2a82d4). Sorry for the inconvenience.
