### ISSUE TITLE
DB Index problem on upgrade from 27.1.15 to 28.0.1

### ISSUE THREAD

**Issue by mwlczk** [hoellen/docker-nextcloud#59]
Index name "calobjects_index" for table "oc_calendarobjects" collides with the constraint on table "oc_calendarobjectsBroke".

is the message. Droping the index calobjects_index on oc_calendarobjects. Solves the problem.
Maybe it is an upstream problem.

**Comment by mwlczk** [comment]
Droping the index calobjects_index on oc_calendarobjects.an retrying the upgrade solves the problem.

**Comment by hoellen** [comment]
For everyone else, it looks as if there is already an upstream issue: https://github.com/nextcloud/server/issues/41253
