### ISSUE TITLE
Implement glibc

### ISSUE THREAD

**Issue by GUNT0815** [hoellen/docker-nextcloud#9]
The new app Recognize (https://apps.nextcloud.com/apps/recognize) needs glibc. So it would be beneficial if the image would include it.

**Comment by waja** [comment]
which means migrating away from alpine. I would opt for keeping alpine.

**Comment by hoellen** [comment]
@GUNT0815 this should probably help you:
https://github.com/Wonderfall/docker-nextcloud/issues/87
