### ISSUE TITLE
Missing otf in nginx default.conf 29.0.8

### ISSUE THREAD

**Issue by nowheretobefound** [hoellen/docker-nextcloud#91]
Getting this in the Security & setup warnings screen :

'Could not check for otf loading support. Please check manually if your webserver serves `.otf` files. 
'
According to this :
https://docs.nextcloud.com/server/29/admin_manual/installation/nginx.html

There should be both otf and woff2 in nginx default conf

This project config :
`location ~ \.woff2?$ {
            try_files $uri /index.php$uri$is_args$args;
            expires 7d;
            access_log off;
        }
`
From the docs :
`  location ~ \.(otf|woff2?)$ {
        try_files $uri /index.php$request_uri;
        expires 7d;         # Cache-Control policy borrowed from `.htaccess`
        access_log off;     # Optional: Don't log access to assets
    }`

Note the missing otf

**Comment by nowheretobefound** [comment]
Ref : https://github.com/nextcloud/server/pull/47983

**Comment by hoellen** [comment]
Thanks for reporting. Should be fixed now. 
Ref: 0ed34272f453f16ed0d2aea609e8f1cf9c2fec2a (version-28), 5366528f1ec10822b61a1d6d2960dc8daa2d3042 (version-29), f5bf94fbaf8685c88c02eed9780bdf96bf552248 (master)

**Comment by nowheretobefound** [comment]
Thank you, works fine now.
